"""add_mood_label_and_emoji_to_mood_logs

Revision ID: 06b172b18593
Revises: 9e617536b0da
Create Date: 2025-09-26 21:20:25.657620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06b172b18593'
down_revision = '9e617536b0da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_foods_barcode', table_name='foods')
    op.drop_index('ix_foods_brand', table_name='foods')
    op.drop_index('ix_foods_category', table_name='foods')
    op.drop_index('ix_foods_external_id', table_name='foods')
    op.drop_index('ix_foods_is_popular', table_name='foods')
    op.drop_index('ix_foods_is_verified', table_name='foods')
    op.drop_index('ix_foods_name', table_name='foods')
    op.drop_index('ix_foods_source', table_name='foods')
    op.drop_index('ix_foods_usda_fdc_id', table_name='foods')
    op.drop_table('foods')
    op.drop_index('idx_mood_logs_log_date', table_name='mood_logs')
    op.drop_index('idx_mood_logs_user_id', table_name='mood_logs')
    op.drop_table('mood_logs')
    op.drop_table('onboarding_profiles')
    op.drop_table('exercises')
    op.drop_table('user_health_profile')
    op.drop_table('simple_user_routine_progress')
    op.drop_table('routine_exercises')
    op.drop_table('nutrition_user_routine_progress')
    op.drop_index('idx_fitness_logs_activity_date', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_user_id', table_name='fitness_logs')
    op.drop_table('fitness_logs')
    op.drop_index('idx_water_logs_log_date', table_name='water_logs')
    op.drop_index('idx_water_logs_user_id', table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_table('exercise_logging_categories')
    op.drop_table('routine_workout_days')
    op.drop_index('idx_nutrition_logs_meal_date', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_user_id', table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index('idx_user_weight_logs_log_date', table_name='user_weight_logs')
    op.drop_index('idx_user_weight_logs_user_id', table_name='user_weight_logs')
    op.drop_table('user_weight_logs')
    op.drop_table('users')
    op.drop_table('nutrition_routines')
    op.drop_table('simple_routines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_routines',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('simple_routines_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), server_default=sa.text('4'), autoincrement=False, nullable=False),
    sa.Column('is_template', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='simple_routines_created_by_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='simple_routines_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('nutrition_routines',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('nutrition_routines_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='nutrition_routines_created_by_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nutrition_routines_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_weight_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_weight_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_weight_logs_pkey')
    )
    op.create_index('idx_user_weight_logs_user_id', 'user_weight_logs', ['user_id'], unique=False)
    op.create_index('idx_user_weight_logs_log_date', 'user_weight_logs', ['log_date'], unique=False)
    op.create_table('nutrition_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('meal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meal_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='nutrition_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nutrition_logs_pkey')
    )
    op.create_index('idx_nutrition_logs_user_id', 'nutrition_logs', ['user_id'], unique=False)
    op.create_index('idx_nutrition_logs_meal_date', 'nutrition_logs', ['meal_date'], unique=False)
    op.create_table('routine_workout_days',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('routine_workout_days_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('day_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workout_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['simple_routines.id'], name='routine_workout_days_routine_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='routine_workout_days_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('exercise_logging_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exercise_logging_categories_pkey'),
    sa.UniqueConstraint('name', name='exercise_logging_categories_name_key')
    )
    op.create_table('water_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_ml', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_oz', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('log_type', sa.VARCHAR(length=20), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("log_type::text = ANY (ARRAY['manual'::character varying, 'goal'::character varying, 'reminder'::character varying]::text[])", name='ck_water_logs_log_type'),
    sa.CheckConstraint('amount_ml > 0 AND amount_ml <= 10000', name='ck_water_logs_amount_ml'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='water_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='water_logs_pkey')
    )
    op.create_index('idx_water_logs_user_id', 'water_logs', ['user_id'], unique=False)
    op.create_index('idx_water_logs_log_date', 'water_logs', ['log_date'], unique=False)
    op.create_table('fitness_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calories_burned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activity_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), server_default=sa.text("'kg'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fitness_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fitness_logs_pkey')
    )
    op.create_index('idx_fitness_logs_user_id', 'fitness_logs', ['user_id'], unique=False)
    op.create_index('idx_fitness_logs_activity_date', 'fitness_logs', ['activity_date'], unique=False)
    op.create_table('nutrition_user_routine_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('days_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['nutrition_routines.id'], name='nutrition_user_routine_progress_routine_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='nutrition_user_routine_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nutrition_user_routine_progress_pkey')
    )
    op.create_table('routine_exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workout_day_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reps', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('weight_notes', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('rest_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('logging_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('intensity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pace', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workout_day_id'], ['routine_workout_days.id'], name='routine_exercises_workout_day_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='routine_exercises_pkey')
    )
    op.create_table('simple_user_routine_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workouts_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_workout_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('workouts_skipped', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['simple_routines.id'], name='simple_user_routine_progress_routine_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='simple_user_routine_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='simple_user_routine_progress_pkey')
    )
    op.create_table('user_health_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('current_weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activity_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_health_profile_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_health_profile_pkey'),
    sa.UniqueConstraint('user_id', name='user_health_profile_user_id_key')
    )
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logging_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exercises_pkey')
    )
    op.create_table('onboarding_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='onboarding_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='onboarding_profiles_user_id_key')
    )
    op.create_table('mood_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mood_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mood_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mood_logs_pkey')
    )
    op.create_index('idx_mood_logs_user_id', 'mood_logs', ['user_id'], unique=False)
    op.create_index('idx_mood_logs_log_date', 'mood_logs', ['log_date'], unique=False)
    op.create_table('foods',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('usda_fdc_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('calories_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('protein_per_100g', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('carbs_per_100g', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('fat_per_100g', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('fiber_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calcium_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iron_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vitamin_c_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vitamin_d_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('common_serving_sizes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('default_serving_grams', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('100'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allergens', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dietary_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_popular', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('foods_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='foods_pkey'),
    sa.UniqueConstraint('barcode', name='foods_barcode_key'),
    sa.UniqueConstraint('usda_fdc_id', name='foods_usda_fdc_id_key')
    )
    op.create_index('ix_foods_usda_fdc_id', 'foods', ['usda_fdc_id'], unique=False)
    op.create_index('ix_foods_source', 'foods', ['source'], unique=False)
    op.create_index('ix_foods_name', 'foods', ['name'], unique=False)
    op.create_index('ix_foods_is_verified', 'foods', ['is_verified'], unique=False)
    op.create_index('ix_foods_is_popular', 'foods', ['is_popular'], unique=False)
    op.create_index('ix_foods_external_id', 'foods', ['external_id'], unique=False)
    op.create_index('ix_foods_category', 'foods', ['category'], unique=False)
    op.create_index('ix_foods_brand', 'foods', ['brand'], unique=False)
    op.create_index('ix_foods_barcode', 'foods', ['barcode'], unique=False)
    # ### end Alembic commands ###
