"""fix_routine_table_name_mismatch

Revision ID: 0a28c19ec001
Revises: dcec4a05b40a
Create Date: 2025-10-13 13:02:36.731489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a28c19ec001'
down_revision = 'dcec4a05b40a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_bridge')
    op.drop_table('exercises_backup')
    op.drop_table('exercises')
    op.drop_index('ix_routines_is_active', table_name='routines')
    op.drop_index('ix_routines_routine_type', table_name='routines')
    op.drop_index('ix_routines_user_id', table_name='routines')
    op.drop_index('ix_routines_user_type_active', table_name='routines')
    op.drop_table('routines')
    op.drop_table('nutrition_routines')
    op.drop_index('idx_user_weight_logs_log_date', table_name='user_weight_logs')
    op.drop_index('idx_user_weight_logs_user_id', table_name='user_weight_logs')
    op.drop_table('user_weight_logs')
    op.drop_index('ix_foods_barcode', table_name='foods')
    op.drop_index('ix_foods_brand', table_name='foods')
    op.drop_index('ix_foods_category', table_name='foods')
    op.drop_index('ix_foods_external_id', table_name='foods')
    op.drop_index('ix_foods_is_popular', table_name='foods')
    op.drop_index('ix_foods_is_verified', table_name='foods')
    op.drop_index('ix_foods_name', table_name='foods')
    op.drop_index('ix_foods_source', table_name='foods')
    op.drop_index('ix_foods_usda_fdc_id', table_name='foods')
    op.drop_table('foods')
    op.drop_index('ix_unified_health_logs_log_date', table_name='unified_health_logs')
    op.drop_index('ix_unified_health_logs_log_type', table_name='unified_health_logs')
    op.drop_index('ix_unified_health_logs_user_id', table_name='unified_health_logs')
    op.drop_index('ix_unified_health_logs_user_log_type_date', table_name='unified_health_logs')
    op.drop_table('unified_health_logs')
    op.drop_table('exercise_lookup')
    op.drop_index('idx_users_deleted_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_nutrition_logs_calories', table_name='nutrition_logs', postgresql_where='(total_calories > 0)')
    op.drop_index('idx_nutrition_logs_calories_range', table_name='nutrition_logs', postgresql_where='(total_calories > 0)')
    op.drop_index('idx_nutrition_logs_created_by', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_deleted_at', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_high_protein', table_name='nutrition_logs', postgresql_where='(protein_g > (20)::double precision)')
    op.drop_index('idx_nutrition_logs_meal_date', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_meal_type', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_user_date', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_user_date_type', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_user_id', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_user_meal_date', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logs_user_type_date', table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index('idx_fitness_logs_activity_date', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_activity_type', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_calories', table_name='fitness_logs', postgresql_where='(calories_burned IS NOT NULL)')
    op.drop_index('idx_fitness_logs_created_by', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_deleted_at', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_duration', table_name='fitness_logs', postgresql_where='(duration_minutes > 0)')
    op.drop_index('idx_fitness_logs_high_calories', table_name='fitness_logs', postgresql_where='(calories_burned > 200)')
    op.drop_index('idx_fitness_logs_user_activity_date', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_user_date', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_user_date_type', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_user_id', table_name='fitness_logs')
    op.drop_index('idx_fitness_logs_user_type_date', table_name='fitness_logs')
    op.drop_table('fitness_logs')
    op.drop_index('idx_water_logs_log_date', table_name='water_logs')
    op.drop_index('idx_water_logs_user_date', table_name='water_logs')
    op.drop_index('idx_water_logs_user_id', table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index('idx_mood_logs_log_date', table_name='mood_logs')
    op.drop_index('idx_mood_logs_rating', table_name='mood_logs')
    op.drop_index('idx_mood_logs_user_date', table_name='mood_logs')
    op.drop_index('idx_mood_logs_user_id', table_name='mood_logs')
    op.drop_table('mood_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mood_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('mood_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mood_emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('mood_rating >= 1 AND mood_rating <= 10', name='ck_mood_logs_rating_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_mood_logs_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_mood_logs_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_mood_logs_updated_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mood_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mood_logs_pkey'),
    sa.UniqueConstraint('uuid', name='uq_mood_logs_uuid')
    )
    op.create_index('idx_mood_logs_user_id', 'mood_logs', ['user_id'], unique=False)
    op.create_index('idx_mood_logs_user_date', 'mood_logs', ['user_id', sa.text('log_date DESC')], unique=False)
    op.create_index('idx_mood_logs_rating', 'mood_logs', ['mood_rating', sa.text('log_date DESC')], unique=False)
    op.create_index('idx_mood_logs_log_date', 'mood_logs', ['log_date'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_ml', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_oz', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('log_type', sa.VARCHAR(length=20), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("log_type::text = ANY (ARRAY['manual'::character varying, 'goal'::character varying, 'reminder'::character varying]::text[])", name='ck_water_logs_log_type'),
    sa.CheckConstraint('amount_ml > 0 AND amount_ml <= 10000', name='ck_water_logs_amount_ml'),
    sa.CheckConstraint('amount_ml > 0 AND amount_ml <= 10000', name='ck_water_logs_amount_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_water_logs_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_water_logs_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_water_logs_updated_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='water_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='water_logs_pkey'),
    sa.UniqueConstraint('uuid', name='uq_water_logs_uuid')
    )
    op.create_index('idx_water_logs_user_id', 'water_logs', ['user_id'], unique=False)
    op.create_index('idx_water_logs_user_date', 'water_logs', ['user_id', 'log_date'], unique=False)
    op.create_index('idx_water_logs_log_date', 'water_logs', ['log_date'], unique=False)
    op.create_table('fitness_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calories_burned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activity_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), server_default=sa.text("'kg'::character varying"), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('calories_burned >= 0', name='ck_fitness_logs_calories_non_negative'),
    sa.CheckConstraint('deleted_at IS NULL OR deleted_by IS NOT NULL', name='ck_fitness_logs_soft_delete'),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 1440', name='ck_fitness_logs_duration_positive'),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 1440', name='ck_fitness_logs_duration_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_fitness_logs_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_fitness_logs_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_fitness_logs_updated_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fitness_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fitness_logs_pkey'),
    sa.UniqueConstraint('uuid', name='uq_fitness_logs_uuid')
    )
    op.create_index('idx_fitness_logs_user_type_date', 'fitness_logs', ['user_id', 'activity_type', sa.text('activity_date DESC')], unique=False)
    op.create_index('idx_fitness_logs_user_id', 'fitness_logs', ['user_id'], unique=False)
    op.create_index('idx_fitness_logs_user_date_type', 'fitness_logs', ['user_id', 'activity_date', 'activity_type'], unique=False)
    op.create_index('idx_fitness_logs_user_date', 'fitness_logs', ['user_id', sa.text('activity_date DESC')], unique=False)
    op.create_index('idx_fitness_logs_user_activity_date', 'fitness_logs', ['user_id', 'activity_date'], unique=False)
    op.create_index('idx_fitness_logs_high_calories', 'fitness_logs', ['user_id', sa.text('activity_date DESC')], unique=False, postgresql_where='(calories_burned > 200)')
    op.create_index('idx_fitness_logs_duration', 'fitness_logs', ['duration_minutes'], unique=False, postgresql_where='(duration_minutes > 0)')
    op.create_index('idx_fitness_logs_deleted_at', 'fitness_logs', ['deleted_at'], unique=False)
    op.create_index('idx_fitness_logs_created_by', 'fitness_logs', ['created_by'], unique=False)
    op.create_index('idx_fitness_logs_calories', 'fitness_logs', ['calories_burned'], unique=False, postgresql_where='(calories_burned IS NOT NULL)')
    op.create_index('idx_fitness_logs_activity_type', 'fitness_logs', ['activity_type', sa.text('activity_date DESC')], unique=False)
    op.create_index('idx_fitness_logs_activity_date', 'fitness_logs', ['activity_date'], unique=False)
    op.create_table('nutrition_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('meal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meal_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('food_items', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fiber_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.CheckConstraint('deleted_at IS NULL OR deleted_by IS NOT NULL', name='ck_nutrition_logs_soft_delete'),
    sa.CheckConstraint('protein_g >= 0::double precision AND carbs_g >= 0::double precision AND fat_g >= 0::double precision', name='ck_nutrition_logs_macros_non_negative'),
    sa.CheckConstraint('total_calories >= 0 AND total_calories <= 10000', name='ck_nutrition_logs_calories_range'),
    sa.CheckConstraint('total_calories >= 0', name='ck_nutrition_logs_calories_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_nutrition_logs_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_nutrition_logs_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_nutrition_logs_updated_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='nutrition_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nutrition_logs_pkey'),
    sa.UniqueConstraint('uuid', name='uq_nutrition_logs_uuid')
    )
    op.create_index('idx_nutrition_logs_user_type_date', 'nutrition_logs', ['user_id', 'meal_type', sa.text('meal_date DESC')], unique=False)
    op.create_index('idx_nutrition_logs_user_meal_date', 'nutrition_logs', ['user_id', 'meal_date'], unique=False)
    op.create_index('idx_nutrition_logs_user_id', 'nutrition_logs', ['user_id'], unique=False)
    op.create_index('idx_nutrition_logs_user_date_type', 'nutrition_logs', ['user_id', 'meal_date', 'meal_type'], unique=False)
    op.create_index('idx_nutrition_logs_user_date', 'nutrition_logs', ['user_id', sa.text('meal_date DESC')], unique=False)
    op.create_index('idx_nutrition_logs_meal_type', 'nutrition_logs', ['meal_type', sa.text('meal_date DESC')], unique=False)
    op.create_index('idx_nutrition_logs_meal_date', 'nutrition_logs', ['meal_date'], unique=False)
    op.create_index('idx_nutrition_logs_high_protein', 'nutrition_logs', ['user_id', sa.text('meal_date DESC')], unique=False, postgresql_where='(protein_g > (20)::double precision)')
    op.create_index('idx_nutrition_logs_deleted_at', 'nutrition_logs', ['deleted_at'], unique=False)
    op.create_index('idx_nutrition_logs_created_by', 'nutrition_logs', ['created_by'], unique=False)
    op.create_index('idx_nutrition_logs_calories_range', 'nutrition_logs', ['total_calories'], unique=False, postgresql_where='(total_calories > 0)')
    op.create_index('idx_nutrition_logs_calories', 'nutrition_logs', ['total_calories'], unique=False, postgresql_where='(total_calories > 0)')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_routine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('health_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('onboarding_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('goals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint('deleted_at IS NULL OR deleted_by IS NOT NULL', name='ck_users_soft_delete'),
    sa.ForeignKeyConstraint(['active_routine_id'], ['routines.id'], name='fk_users_active_routine_id'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_users_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_users_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_users_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('uuid', name='uq_users_uuid'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_table('exercise_lookup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exercise_db_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body_part', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('equipment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_muscle', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('gif_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secondary_muscles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggested_logging_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exercise_lookup_pkey')
    )
    op.create_table('unified_health_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('log_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('log_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mood_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('water_amount_ml', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='unified_health_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='unified_health_logs_pkey')
    )
    op.create_index('ix_unified_health_logs_user_log_type_date', 'unified_health_logs', ['user_id', 'log_type', 'log_date'], unique=False)
    op.create_index('ix_unified_health_logs_user_id', 'unified_health_logs', ['user_id'], unique=False)
    op.create_index('ix_unified_health_logs_log_type', 'unified_health_logs', ['log_type'], unique=False)
    op.create_index('ix_unified_health_logs_log_date', 'unified_health_logs', ['log_date'], unique=False)
    op.create_table('foods',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('usda_fdc_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('calories_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('protein_per_100g', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('carbs_per_100g', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('fat_per_100g', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('fiber_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calcium_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iron_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vitamin_c_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vitamin_d_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('common_serving_sizes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('default_serving_grams', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('100'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allergens', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dietary_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_popular', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('foods_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_type', sa.VARCHAR(length=20), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_foods_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_foods_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_foods_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='foods_pkey'),
    sa.UniqueConstraint('barcode', name='foods_barcode_key'),
    sa.UniqueConstraint('usda_fdc_id', name='foods_usda_fdc_id_key'),
    sa.UniqueConstraint('uuid', name='uq_foods_uuid')
    )
    op.create_index('ix_foods_usda_fdc_id', 'foods', ['usda_fdc_id'], unique=False)
    op.create_index('ix_foods_source', 'foods', ['source'], unique=False)
    op.create_index('ix_foods_name', 'foods', ['name'], unique=False)
    op.create_index('ix_foods_is_verified', 'foods', ['is_verified'], unique=False)
    op.create_index('ix_foods_is_popular', 'foods', ['is_popular'], unique=False)
    op.create_index('ix_foods_external_id', 'foods', ['external_id'], unique=False)
    op.create_index('ix_foods_category', 'foods', ['category'], unique=False)
    op.create_index('ix_foods_brand', 'foods', ['brand'], unique=False)
    op.create_index('ix_foods_barcode', 'foods', ['barcode'], unique=False)
    op.create_table('user_weight_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_user_weight_logs_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_user_weight_logs_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_user_weight_logs_updated_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_weight_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_weight_logs_pkey'),
    sa.UniqueConstraint('uuid', name='uq_user_weight_logs_uuid')
    )
    op.create_index('idx_user_weight_logs_user_id', 'user_weight_logs', ['user_id'], unique=False)
    op.create_index('idx_user_weight_logs_log_date', 'user_weight_logs', ['log_date'], unique=False)
    op.create_table('nutrition_routines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_nutrition_routines_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='nutrition_routines_created_by_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_nutrition_routines_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_nutrition_routines_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='nutrition_routines_pkey'),
    sa.UniqueConstraint('uuid', name='uq_nutrition_routines_uuid')
    )
    op.create_table('routines',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('routines_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('routine_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('workout_days', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exercises', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('nutrition_plan', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('progress_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='routines_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='routines_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_routines_user_type_active', 'routines', ['user_id', 'routine_type', 'is_active'], unique=False)
    op.create_index('ix_routines_user_id', 'routines', ['user_id'], unique=False)
    op.create_index('ix_routines_routine_type', 'routines', ['routine_type'], unique=False)
    op.create_index('ix_routines_is_active', 'routines', ['is_active'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('exercises_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logging_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_exercises_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_exercises_deleted_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_exercises_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='exercises_pkey'),
    sa.UniqueConstraint('uuid', name='uq_exercises_uuid'),
    postgresql_ignore_search_path=False
    )
    op.create_table('exercises_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('logging_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('exercise_bridge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exercise_db_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('your_db_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('match_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['your_db_id'], ['exercises.id'], name='exercise_bridge_your_db_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='exercise_bridge_pkey')
    )
    # ### end Alembic commands ###
