"""init schema

Revision ID: 487eac5fa7c9
Revises: 
Create Date: 2025-08-10 20:33:58.953254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487eac5fa7c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('faiss_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('memory_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_nodes_conversation_id'), 'memory_nodes', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_nodes_faiss_id'), 'memory_nodes', ['faiss_id'], unique=True)
    op.create_index(op.f('ix_memory_nodes_user_id'), 'memory_nodes', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('onboarding_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('topics_json', sa.Text(), nullable=True),
    sa.Column('hobbies', sa.Text(), nullable=True),
    sa.Column('favorites', sa.Text(), nullable=True),
    sa.Column('response_style', sa.String(), nullable=True),
    sa.Column('tone_json', sa.Text(), nullable=True),
    sa.Column('small_talk_level', sa.Integer(), nullable=True),
    sa.Column('primary_reason', sa.String(), nullable=True),
    sa.Column('personal_goals', sa.Text(), nullable=True),
    sa.Column('checkins_enabled', sa.Boolean(), nullable=True),
    sa.Column('avoid_topics', sa.Text(), nullable=True),
    sa.Column('memory_policy', sa.String(), nullable=True),
    sa.Column('recall_enabled', sa.Boolean(), nullable=True),
    sa.Column('dream_trip', sa.String(), nullable=True),
    sa.Column('random_fact', sa.Text(), nullable=True),
    sa.Column('ai_persona', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_profiles_id'), 'onboarding_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_profiles_user_id'), 'onboarding_profiles', ['user_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_onboarding_profiles_user_id'), table_name='onboarding_profiles')
    op.drop_index(op.f('ix_onboarding_profiles_id'), table_name='onboarding_profiles')
    op.drop_table('onboarding_profiles')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_memory_nodes_user_id'), table_name='memory_nodes')
    op.drop_index(op.f('ix_memory_nodes_faiss_id'), table_name='memory_nodes')
    op.drop_index(op.f('ix_memory_nodes_conversation_id'), table_name='memory_nodes')
    op.drop_table('memory_nodes')
    # ### end Alembic commands ###
