"""add_active_routine_id_to_user

Revision ID: 7444bc457e38
Revises: 55f8f148215b
Create Date: 2025-10-04 20:10:06.269115

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7444bc457e38'
down_revision = '55f8f148215b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_routine_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_routine_id')
    # ### end Alembic commands ###