"""Add exercise logging categories based on attributes

Revision ID: d6e83c5521c4
Revises: c1a66bda425e
Create Date: 2025-09-19 18:53:46.230693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6e83c5521c4'
down_revision = 'c1a66bda425e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nutrition_logs_user_id', table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_exercises_category', table_name='exercises')
    op.drop_index('ix_exercises_category_difficulty', table_name='exercises')
    op.drop_index('ix_exercises_is_popular', table_name='exercises')
    op.drop_index('ix_exercises_name', table_name='exercises')
    op.drop_index('ix_exercises_popular', table_name='exercises')
    op.drop_index('ix_exercises_wger_id', table_name='exercises')
    op.drop_index('ix_exercises_wger_uuid', table_name='exercises')
    op.drop_table('exercises')
    op.drop_index('ix_mood_logs_user_id', table_name='mood_logs')
    op.drop_table('mood_logs')
    op.drop_index('idx_food_log_items_created_at', table_name='food_log_items')
    op.drop_index('idx_food_log_items_food_id', table_name='food_log_items')
    op.drop_index('idx_food_log_items_nutrition_log_id', table_name='food_log_items')
    op.drop_index('ix_food_log_items_food_id', table_name='food_log_items')
    op.drop_index('ix_food_log_items_nutrition_log_id', table_name='food_log_items')
    op.drop_table('food_log_items')
    op.drop_index('ix_user_weight_logs_user_id', table_name='user_weight_logs')
    op.drop_table('user_weight_logs')
    op.drop_table('simple_routines')
    op.drop_table('simple_user_routine_progress')
    op.drop_index('ix_user_food_history_food_id', table_name='user_food_history')
    op.drop_index('ix_user_food_history_user_id', table_name='user_food_history')
    op.drop_index('ix_user_food_last_logged', table_name='user_food_history')
    op.drop_index('ix_user_food_unique', table_name='user_food_history')
    op.drop_table('user_food_history')
    op.drop_table('routine_workout_days')
    op.drop_table('workout_categories')
    op.drop_index('ix_user_health_profile_user_id', table_name='user_health_profile')
    op.drop_table('user_health_profile')
    op.drop_table('routine_exercises')
    op.drop_index('ix_user_exercise_history_exercise_id', table_name='user_exercise_history')
    op.drop_index('ix_user_exercise_history_user_id', table_name='user_exercise_history')
    op.drop_index('ix_user_exercise_last_performed', table_name='user_exercise_history')
    op.drop_index('ix_user_exercise_unique', table_name='user_exercise_history')
    op.drop_table('user_exercise_history')
    op.drop_table('nutrition_routines')
    op.drop_table('nutrition_user_routine_progress')
    op.drop_index('ix_foods_barcode', table_name='foods')
    op.drop_index('ix_foods_brand', table_name='foods')
    op.drop_index('ix_foods_brand_category', table_name='foods')
    op.drop_index('ix_foods_category', table_name='foods')
    op.drop_index('ix_foods_category_verified', table_name='foods')
    op.drop_index('ix_foods_is_popular', table_name='foods')
    op.drop_index('ix_foods_is_verified', table_name='foods')
    op.drop_index('ix_foods_name', table_name='foods')
    op.drop_index('ix_foods_name_brand', table_name='foods')
    op.drop_index('ix_foods_popular_usage', table_name='foods')
    op.drop_index('ix_foods_usda_fdc_id', table_name='foods')
    op.drop_table('foods')
    op.drop_index('ix_fitness_logs_user_id', table_name='fitness_logs')
    op.drop_table('fitness_logs')
    op.drop_table('onboarding_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('memory_chunks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('structured_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('daily_schedule', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('schedule_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fitness_goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nutrition_goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dietary_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('communication_style', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='onboarding_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='onboarding_profiles_user_id_key')
    )
    op.create_table('fitness_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('intensity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('calories_burned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activity_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("intensity::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])", name='ck_fitness_logs_intensity'),
    sa.CheckConstraint('calories_burned >= 0', name='ck_fitness_logs_calories'),
    sa.CheckConstraint('distance_km >= 0::double precision', name='ck_fitness_logs_distance'),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 1440', name='ck_fitness_logs_duration'),
    sa.CheckConstraint('reps >= 0', name='ck_fitness_logs_reps'),
    sa.CheckConstraint('sets >= 0', name='ck_fitness_logs_sets'),
    sa.CheckConstraint('weight_kg >= 0::double precision', name='ck_fitness_logs_weight'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fitness_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fitness_logs_pkey')
    )
    op.create_index('ix_fitness_logs_user_id', 'fitness_logs', ['user_id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('foods_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('usda_fdc_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('calories_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('protein_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fiber_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calcium_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iron_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vitamin_c_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vitamin_d_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('common_serving_sizes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('default_serving_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allergens', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dietary_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_popular', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='foods_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_foods_usda_fdc_id', 'foods', ['usda_fdc_id'], unique=False)
    op.create_index('ix_foods_popular_usage', 'foods', ['is_popular', 'usage_count'], unique=False)
    op.create_index('ix_foods_name_brand', 'foods', ['name', 'brand'], unique=False)
    op.create_index('ix_foods_name', 'foods', ['name'], unique=False)
    op.create_index('ix_foods_is_verified', 'foods', ['is_verified'], unique=False)
    op.create_index('ix_foods_is_popular', 'foods', ['is_popular'], unique=False)
    op.create_index('ix_foods_category_verified', 'foods', ['category', 'is_verified'], unique=False)
    op.create_index('ix_foods_category', 'foods', ['category'], unique=False)
    op.create_index('ix_foods_brand_category', 'foods', ['brand', 'category'], unique=False)
    op.create_index('ix_foods_brand', 'foods', ['brand'], unique=False)
    op.create_index('ix_foods_barcode', 'foods', ['barcode'], unique=True)
    op.create_table('nutrition_user_routine_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('meals_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('days_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_meal_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['nutrition_routines.id'], name='nutrition_user_routine_progress_routine_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='nutrition_user_routine_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nutrition_user_routine_progress_pkey')
    )
    op.create_table('nutrition_routines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('meal_plans', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='nutrition_routines_created_by_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nutrition_routines_pkey')
    )
    op.create_table('user_exercise_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('times_performed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_performed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('avg_duration_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_calories_burned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('best_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preferred_intensity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='user_exercise_history_exercise_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_exercise_history_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_exercise_history_pkey')
    )
    op.create_index('ix_user_exercise_unique', 'user_exercise_history', ['user_id', 'exercise_id'], unique=True)
    op.create_index('ix_user_exercise_last_performed', 'user_exercise_history', ['user_id', 'last_performed'], unique=False)
    op.create_index('ix_user_exercise_history_user_id', 'user_exercise_history', ['user_id'], unique=False)
    op.create_index('ix_user_exercise_history_exercise_id', 'user_exercise_history', ['exercise_id'], unique=False)
    op.create_table('routine_exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workout_day_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reps', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('weight_notes', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('rest_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workout_day_id'], ['routine_workout_days.id'], name='routine_exercises_workout_day_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='routine_exercises_pkey')
    )
    op.create_table('user_health_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('activity_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('current_weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_health_profile_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_health_profile_pkey')
    )
    op.create_index('ix_user_health_profile_user_id', 'user_health_profile', ['user_id'], unique=False)
    op.create_table('workout_categories',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='workout_categories_pkey')
    )
    op.create_table('routine_workout_days',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('day_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workout_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['simple_routines.id'], name='routine_workout_days_routine_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='routine_workout_days_pkey')
    )
    op.create_table('user_food_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('times_logged', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_logged', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('avg_serving_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('most_common_meal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('preferred_serving_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name='user_food_history_food_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_food_history_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_food_history_pkey')
    )
    op.create_index('ix_user_food_unique', 'user_food_history', ['user_id', 'food_id'], unique=True)
    op.create_index('ix_user_food_last_logged', 'user_food_history', ['user_id', 'last_logged'], unique=False)
    op.create_index('ix_user_food_history_user_id', 'user_food_history', ['user_id'], unique=False)
    op.create_index('ix_user_food_history_food_id', 'user_food_history', ['food_id'], unique=False)
    op.create_table('simple_user_routine_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workouts_completed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_workout_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['simple_routines.id'], name='simple_user_routine_progress_routine_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='simple_user_routine_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='simple_user_routine_progress_pkey')
    )
    op.create_table('simple_routines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='simple_routines_created_by_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='simple_routines_pkey')
    )
    op.create_table('user_weight_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('body_fat_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('muscle_mass_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('waist_circumference_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hip_circumference_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_weight_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_weight_logs_pkey')
    )
    op.create_index('ix_user_weight_logs_user_id', 'user_weight_logs', ['user_id'], unique=False)
    op.create_table('food_log_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nutrition_log_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('quantity_grams', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('calories', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('protein_g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('carbs_g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fat_g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fiber_g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sugar_g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sodium_mg', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('calories >= 0::numeric', name='ck_food_log_items_calories_positive'),
    sa.CheckConstraint('carbs_g >= 0::numeric', name='ck_food_log_items_carbs_positive'),
    sa.CheckConstraint('fat_g >= 0::numeric', name='ck_food_log_items_fat_positive'),
    sa.CheckConstraint('fiber_g >= 0::numeric', name='ck_food_log_items_fiber_positive'),
    sa.CheckConstraint('protein_g >= 0::numeric', name='ck_food_log_items_protein_positive'),
    sa.CheckConstraint('quantity_grams > 0::numeric', name='ck_food_log_items_quantity_positive'),
    sa.CheckConstraint('sodium_mg >= 0::numeric', name='ck_food_log_items_sodium_positive'),
    sa.CheckConstraint('sugar_g >= 0::numeric', name='ck_food_log_items_sugar_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name='food_log_items_food_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutrition_log_id'], ['nutrition_logs.id'], name='food_log_items_nutrition_log_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='food_log_items_pkey')
    )
    op.create_index('ix_food_log_items_nutrition_log_id', 'food_log_items', ['nutrition_log_id'], unique=False)
    op.create_index('ix_food_log_items_food_id', 'food_log_items', ['food_id'], unique=False)
    op.create_index('idx_food_log_items_nutrition_log_id', 'food_log_items', ['nutrition_log_id'], unique=False)
    op.create_index('idx_food_log_items_food_id', 'food_log_items', ['food_id'], unique=False)
    op.create_index('idx_food_log_items_created_at', 'food_log_items', ['created_at'], unique=False)
    op.create_table('mood_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mood_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('energy_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water_intake_ml', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steps_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('energy_level >= 1 AND energy_level <= 10', name='ck_mood_logs_energy'),
    sa.CheckConstraint('mood_rating >= 1 AND mood_rating <= 10', name='ck_mood_logs_rating'),
    sa.CheckConstraint('sleep_hours >= 0::double precision AND sleep_hours <= 24::double precision', name='ck_mood_logs_sleep_hours'),
    sa.CheckConstraint('sleep_quality >= 1 AND sleep_quality <= 10', name='ck_mood_logs_sleep_quality'),
    sa.CheckConstraint('steps_count >= 0', name='ck_mood_logs_steps'),
    sa.CheckConstraint('stress_level >= 1 AND stress_level <= 10', name='ck_mood_logs_stress'),
    sa.CheckConstraint('water_intake_ml >= 0', name='ck_mood_logs_water'),
    sa.CheckConstraint('weight_kg >= 0::double precision', name='ck_mood_logs_weight'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mood_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mood_logs_pkey')
    )
    op.create_index('ix_mood_logs_user_id', 'mood_logs', ['user_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('muscle_groups', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('equipment_needed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('calories_per_minute', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('met_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instructions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tips', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('variations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_popular', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wger_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wger_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('wger_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wger_license_author', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='exercises_pkey')
    )
    op.create_index('ix_exercises_wger_uuid', 'exercises', ['wger_uuid'], unique=False)
    op.create_index('ix_exercises_wger_id', 'exercises', ['wger_id'], unique=False)
    op.create_index('ix_exercises_popular', 'exercises', ['is_popular', 'usage_count'], unique=False)
    op.create_index('ix_exercises_name', 'exercises', ['name'], unique=False)
    op.create_index('ix_exercises_is_popular', 'exercises', ['is_popular'], unique=False)
    op.create_index('ix_exercises_category_difficulty', 'exercises', ['category', 'difficulty_level'], unique=False)
    op.create_index('ix_exercises_category', 'exercises', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('memory_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('nutrition_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('meal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fiber_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('food_items', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mood_before', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mood_after', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('meal_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("meal_type::text = ANY (ARRAY['breakfast'::character varying, 'lunch'::character varying, 'dinner'::character varying, 'snack'::character varying]::text[])", name='ck_nutrition_logs_meal_type'),
    sa.CheckConstraint('carbs_g >= 0::double precision', name='ck_nutrition_logs_carbs'),
    sa.CheckConstraint('fat_g >= 0::double precision', name='ck_nutrition_logs_fat'),
    sa.CheckConstraint('fiber_g >= 0::double precision', name='ck_nutrition_logs_fiber'),
    sa.CheckConstraint('protein_g >= 0::double precision', name='ck_nutrition_logs_protein'),
    sa.CheckConstraint('sodium_mg >= 0::double precision', name='ck_nutrition_logs_sodium'),
    sa.CheckConstraint('sugar_g >= 0::double precision', name='ck_nutrition_logs_sugar'),
    sa.CheckConstraint('total_calories >= 0', name='ck_nutrition_logs_calories'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='nutrition_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nutrition_logs_pkey')
    )
    op.create_index('ix_nutrition_logs_user_id', 'nutrition_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###
