"""add onboarding_profiles

Revision ID: fad26210c922
Revises: 1234abcd5678
Create Date: 2025-08-10 04:50:53.416445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad26210c922'
down_revision = '1234abcd5678'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('embedding', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
